language:
  node_js
  - 9
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g angular-cli codecov

jobs:
  include:
    - stage: build dev
      script: npm run build && npm run lint && npm test && codecov
    - stage: build prod
      script: npm run build --aot --prod && npm run lint && npm test
