# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: 1001

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/New_York

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm run build --verbose

    - name: Run Lint Checks
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Run e2e tests
      run: npm run test:e2e
